# Starship command prompt configuration file. Colour choice and over-use of emoji
# is to help blend in with Ubuntu MATE default theme, Ambiant-Mate.


# disable starship from forcing a new line to be taken. Solved the empty line 
# at start of terminal
add_newline = true

[line_break]
disabled = false

[aws]
disabled = true

[character]      # The name of the module we are configuring is "character"
error_symbol = "[✖](bold red) "

[cmd_duration]
min_time = 5_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "
style = "bold italic red"

[conda]
format = "via [$environment]($style) "

[directory]
truncation_length = 5
truncate_to_repo = false # truncates directory to root folder if in github repo
style = "bold italic #87A752"
format = "[${path}]($style)[$read_only]($read_only_style) "

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold purple"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

# shows the hostname on new lines
[hostname]
ssh_only = true
disabled = false
style = "bold italic #87A752"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[nodejs]
disabled = true

[python]
format = '[Python (${version})]($style) '
style = "blue"
pyenv_version_name = true


[rust]
format = "[$symbol$version]($style) "
style = "bold green"

# Hide the username. The username will only show in certain scenarios
[username]
disabled = true
